# -*- coding: utf-8 -*-
"""Datasciencelifecycle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jaduWb8O5DJXAMk-CMhGAcxCCYeNprX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_excel("/content/II CSE C -mark.xlsx")

df['Total'] = df[['Toc', 'Java', 'Ml', 'CS', 'SE', 'CN']].sum(axis=1)
df['Average'] = df['Total'] / 6

highest = df.loc[df['Total'].idxmax()]
lowest = df.loc[df['Total'].idxmin()]

# For middle, we'll find the student whose total is closest to the median total
median_total = df['Total'].median()
middle = df.iloc[(df['Total'] - median_total).abs().argsort()[:1]].squeeze()

print("===== HIGHEST MARK STUDENT ====")
print("Name   :", highest['Student Name'])
print("Roll No:", highest['Roll No'])
print("Total  :", highest['Total'])
print("Average:", round(highest['Average'], 2))

print("\n===== MIDDLE MARK STUDENT ====")
print("Name   :", middle['Student Name'])
print("Roll No:", middle['Roll No'])
print("Total  :", middle['Total'])
print("Average:", round(middle['Average'], 2))

print("\n===== LOWEST MARK STUDENT ====")
print("Name   :", lowest['Student Name'])
print("Roll No:", lowest['Roll No'])
print("Total  :", lowest['Total'])
print("Average:", round(lowest['Average'], 2))

performance = pd.DataFrame({
    'Student': [highest['Student Name'], middle['Student Name'], lowest['Student Name']],
    'Total Marks': [highest['Total'], middle['Total'], lowest['Total']]
})

plt.figure(figsize=(6,6))
plt.pie(
    performance['Total Marks'],
    labels=performance['Student'],
    autopct='%1.1f%%'
)
plt.title("Performance Comparison")
plt.show()

print(df.describe())